name: dispatch-rss-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Trigger Git RSS
      run: |
        ./.github/trigger_rss_gen.sh
      env:
        DISPATCH_ACTION_TOKEN: ${{ secrets.DISPATCH_ACTION_TOKEN }}
